### ISSUE TITLE
ClojureCLR-1.5.0.zip is slightly out of date

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#106]
I think ClojureCLR-1.5.0.zip is slightly out of date from what is being shipped via the Nuget ClojureCLR package.

**Comment by frankhale** [comment]
the latest version of ClojureCLR is:

```
C:\Users\fhale\Desktop\temp>nuget install clojure
Installing 'Clojure 1.5.0.2'.
Successfully installed 'Clojure 1.5.0.2'.
```

**Comment by frankhale** [comment]
This has been updated.

**Comment by speige** [comment]
Fyi, the runtime used by vsclojure had a modification to the clojure compiler to allow adding project references between c# projects and clojure projects.

The changes have been submitted to David miller, but have not yet been incorporated into clojureClr because they caused a unit test to fail.

We'll want to check that the project references still work before we close this bug & before we submit a new version to the gallery.

**Comment by speige** [comment]
It looks like this did break compilation of .cljproj files. I'll fork the ClojureCLR github repo & commit my changes so they're documented.

Should we revert the ClojureCLR-1.5.0.zip in the meantime?

**Comment by frankhale** [comment]
I've reverted. It'd be great to create a page in the Wiki to document the changes from the upstream ClojureCLR.
