### ISSUE TITLE
ClojureCLR custom patch

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#116]
We need to document the custom patch that we are using so that we can merge that patch into the latest ClojureCLR code so that we can ship the latest version of ClojureCLR with vsClojure.

**Comment by frankhale** [comment]
@speige, do you mind putting a reference to the patch here so that we have it documented? I'd like to grab the patch and apply it to the 1.6 branch.

**Comment by speige** [comment]
The patch is at http://dev.clojure.org/jira/browse/CLJCLR-25

David Miller said it broke 3 unit tests. I need to get those fixed before he'll incorporate the changes into ClojureCLR. However, from my testing I didn't notice any actual issues caused by it.

The other thing is the .dlls have to be signed or they cannot be incorporated into a visual studio extension. Although the nuGet version is signed, the github.com/clojure/clojure-clr repository doesn't have the .snk file (for safety reasons). I've been using the .snk file from the vsClojure repository to sign ClojureCLR (since I have a modified version different than nuGet).

We should probably move the Key.snk out of the vsClojure repository (& regenerate a new one), since GitHub has a private place to store that which only members of the repo can see.

**Comment by frankhale** [comment]
```
The patch is at http://dev.clojure.org/jira/browse/CLJCLR-25
```

Thank you!

```
David Miller said it broke 3 unit tests. I need to get those fixed before he'll incorporate the changes into ClojureCLR. However, from my testing I didn't notice any actual issues caused by it.
```

Did he mention what 3 unit tests were broken? I plan on playing with this shortly.

```
We should probably move the Key.snk out of the vsClojure repository (& regenerate a new one), since GitHub has a private place to store that which only members of the repo can see.
```

Understood. Let's do that. As far as a timeline to complete that I'm not sure, I think it's probably low priority for the immediate future, but maybe not.

**Comment by frankhale** [comment]
While not specifically mentioning the names of the failed tests he did provide some information so disregard that. I'll see if I can get ClojureCLR patched up with your code and see what happens.

**Comment by frankhale** [comment]
This has been docuemented in the wiki:

https://github.com/vsClojure/vsClojure/wiki/Clojure-Patches

Patch is here:

http://dev.clojure.org/jira/secure/attachment/12091/0001-PATCH-Add-NDesk.Options-ManyConsole-via-NuGet-to-all.patch
