### ISSUE TITLE
Add copyright notice and header to each source file

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#120]
Make all the source files consistent by adding a copyright notice and header to each source file.

**Comment by speige** [comment]
Do we need this, or is enough to just have it in the license.txt file?

**Comment by frankhale** [comment]
I think for the most part it's kind of customary to include a header with
info about the file as well as a copy of the license.

**Comment by speige** [comment]
You're right, a lot of open source projects have this. I personally find it annoying, but if you want it on there, I'll follow suit. Were you envisioning the full text, or just a 2-line "Copyright 2010 JMis \r\n MIT License" ?

One thing that bothers me is that the Copyright says JMis. I appreciate his major contribution to the project, but if the project lives on and has many contributors in the future, it seems wrong for the other contributors to not get credit for their work. 

MIT license is essentially the same as Public Domain (because everyone has the right to do anything they want with it), except that it requires attribution. So, essentially the copyright is meaningless because we've given away all rights to the code.

**Comment by frankhale** [comment]
I usually do a shortened form of the license and do kind of what you said "Copyright MIT: see LICENSE.txt" or something like that. I think we should probably just include some kind of information in the README or make an AUTHORS file that denotes JMis role and then remove the name from the license and put something that says "See AUTHORS.txt for a listing of all contributors" or something this way we keep the license verbiage clean while still attributing work to the proper places.

**Comment by speige** [comment]
I like that.

**Comment by speige** [comment]
Although, I guess we really shouldn't change this without JMis permission. I guess we could leave it "Copyright JMis" but still add an Authors.txt or Contributors.txt somewhere.

**Comment by frankhale** [comment]
No worries. I haven't made any modifications to it so it's all good.
