### ISSUE TITLE
Cannot create projects in VS 2013

### ISSUE THREAD

**Issue by markxnelson** [vsClojure/vsClojure#137]
Installed vsClojure from Tools/Extensions in a brand new install of VS 2013.  When I try to create a project, I get an error (see attached image) that this version does not understand cljproj, and I should use another version of VS. 

Visual Studio installation details:

Microsoft Visual Studio Ultimate 2013
Version 12.0.21005.1 REL
Microsoft .NET Framework
Version 4.5.51641

Installed Version: Ultimate

Architecture and Modeling Tools   06181-004-0449004-02874
Microsoft Architecture and Modeling Tools

UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

LightSwitch for Visual Studio 2013   06181-004-0449004-02874
Microsoft LightSwitch for Visual Studio 2013

Microsoft Office Developer Tools for Visual Studio 2013 ENU   06181-004-0449004-02874
Microsoft Office Developer Tools for Visual Studio 2013 ENU

Team Explorer for Visual Studio 2013   06181-004-0449004-02874
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06181-004-0449004-02874
Microsoft Visual Basic 2013

Visual C# 2013   06181-004-0449004-02874
Microsoft Visual C# 2013

Visual C++ 2013   06181-004-0449004-02874
Microsoft Visual C++ 2013

Visual F# 2013   06181-004-0449004-02874
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06181-004-0449004-02874
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Windows Phone SDK 8.0 - ENU   06181-004-0449004-02874
Windows Phone SDK 8.0 - ENU

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.0.11001.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.0
Provides common services for use by Azure Mobile Services and Windows Azure Tools.

Microsoft Advertising SDK for Windows Phone  
Microsoft Advertising SDK for Windows Phone
Build 

Microsoft Python Tools for Visual Studio   2.0.11016.00
Python Tools for Visual Studio provides intellisense, project support, project and item templates, as well as a REPL window for Python development.

Microsoft Python Tools for Visual Studio - Django Integration   2.0.11016.00
Provides templates and integration for the Django web framework.

Microsoft Python Tools for Visual Studio - Profiling Support   2.0.11016.00
Profiling support for Python projects.

Microsoft Web Developer Tools 2013   2.0.40926.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Windows Azure Web Sites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Windows Azure

NuGet Package Manager   2.7.40911.287
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   12.0.30919.1
Microsoft SQL Server Data Tools

Windows Azure Mobile Services Tools   1.0
Windows Azure Mobile Services Tools

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

![vs2013error](https://f.cloud.github.com/assets/6345393/1865452/f1ff3490-780f-11e3-9e8f-ec38b34e3077.png)

**Comment by frankhale** [comment]
This is a long standing problem that has yet to be solved. The message is ambiguous and the message is not related to the fact that the project is not compatible with VS.

Work around: Instead of double clicking on the SLN to open it in VS. Instead open VS and then open the project using File->Open->Project/Solution.

Patches to solve this are certainly welcome!

**Comment by mikewl** [comment]
Mark, can you look at my issue and see if your runtimes have been unzipped?
I get the same error when trying to create a project.

Frank, this happens when trying to create a new project, not open one. I think this is the same issue I am having.

**Comment by frankhale** [comment]
Grab a copy of the code, build it and then install the VSIX file. I am using VS2013 and am able to create projects but I'm not running the copy of vsClojure in the Extension Gallery.

https://github.com/vsClojure/vsClojure/wiki/Building-from-Source-Code

**Comment by mikewl** [comment]
Same as before.
Clean version of windows 8.1 x64 with just drivers and vs 2013 +sdk installed.

The Runtimes are still just zip files, not extracted.

EDIT: Forgot to add on another PC with just vs2012 on I don't have this issue.

**Comment by frankhale** [comment]
Interesting. That is the same setup I have.

**Comment by frankhale** [comment]
Is .NET 3.5 installed?

**Comment by mikewl** [comment]
It was not. Too clean an install. Installing now and will update as soon as it is done (slow internet)

**Comment by markxnelson** [comment]
I unzipped those two files as suggested by mike and issue 136 - after doing that, on starting VS, I get a dialog that says "setup of vsClojure Complete. restart VS".  After I restart, I can create a clojure project.  So that seems to fix the issue.
I am not closing the issue, as there is obviously something wrong in the install process that means these zips are not unzipped.

**Comment by frankhale** [comment]
Internally the unzipping of those files _ought_ to happen on installation and it uses SharpZipLib to do it. That code is wrapped in a try/catch block which apparently isn't throwing an exception otherwise you'd have seen a message box. We have a ticket in to add logging which is sorely needed at this point. It's hard to tell why the unzipping of the runtime files is not happening for you but is happening for me. We have very similiar setups, Win 8.1 x64, VS 2013. I have every version of .NET. I did notice that Windows 8.1 does not install 3.5 by default. You may want to see if 3.5 is installed and if not, install it.

**Comment by speige** [comment]
I created a new virtual machine with only windows 8 x64 and vs2013 Pro. I downloaded vsClojure through tools/extensions in visual studio. It installed normally, including unzipping the files.

If you uninstall/reinstall vsClojure from the gallery, are you still having this issue?

On a side note, it's probably better to use the distributed version from the gallery, rather than compiling the source code from github. Any recent commits to github would be considered unstable and not fully tested, whereas the published version in the visual studio gallery should be considered stable.

Also, you may want to join the Google+ community at gplus.to/clojureclr

**Comment by speige** [comment]
I committed a change that might fix this unzipping issue. Do you want to pull the latest from GitHub, compile, and try it out? Alternatively, I can put the .vsix online somewhere.
