### ISSUE TITLE
Update to latest Clojurescript 0.0-2156

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#140]
Update to latest Clojurescript 0.0-2156

**Comment by frankhale** [comment]
I've got this built and ready for upload.

**Comment by frankhale** [comment]
@speige, I think for the Clojurescript zip file we should remove the 1.5.0 nomenclature that is being borrowed from the ClojureCLR zip file and rename it with the version of Clojurescript that we are including.

So the proposed zip file would look like this:

Clojurescript-0.0-2156.zip

I haven't checked but there should be a variable in the deployment project that denotes the version number so we know what file to unzip.

**Comment by speige** [comment]
Agreed.

Right now the code is in ClojurePackage.CompileClojureScript

It uses Constants.ClojureScript + '-' + Constants.Version to determine the directory.

We should be able to change that pretty easily to a ClojureScript specific version #, rather than using the CLR version #.

Most of the time for the CLR we use an MSBuild property to determine the Clojure version. The only time we use the constant is when loading a REPL. Ideally we should always get it from the MSBuild property, but I haven't researched how to add a new property to the property window for c# projects.

Unless there's a major improvement to this ClojureScript version over the previous, I probably will wait on posting it to the gallery until we have a few more bugs/features finished.

**Comment by frankhale** [comment]
Sorry, I've been so busy lately that I haven't had time to get this uploaded.

**Comment by frankhale** [comment]
I love the fact that doing syncs against the upstream is normally always resulting in merge conflicts. This happens with other repos as well. Maybe I'm doing it all wrong but I am following the instructions on the Github.com page https://help.github.com/articles/syncing-a-fork

Anyway, I guess I'll delete my fork and refork the project. This is making me so angry I can't even see straight.

The latest Clojurescript will be included in just a few minutes.

**Comment by frankhale** [comment]
Please note that I've closed this but there is currently no infrastructure in place to automatically extract this Clojurescript runtime and use it from within vsClojure. You'd have to do some manual work to get it to work.

**Comment by speige** [comment]
Thanks for working on this!

You mentioned the frustrations with pulling forks. I wonder if you're having issues with Linux vs Windows line endings?

I assume you're using windows?

Try this extension, it gives you a GUI in the windows-explorer right-click menu for committing that makes things a lot easier.:
https://code.google.com/p/gitextensions/downloads/detail?name=GitExtensions24703Setup.msi

If you open the settings for it, there is a section called "Global Settings / Line Endings". I have it set to "Checkout as-is, commit as-is ("core.autocrlf" is set to "false")"

Whenever visual studio asks if I want it to normalize my line endings, I say no.

It seems like GitHub prefers Unix-style endings. There is no setting in the GUI to always commit Windows-style. However, I guess we could also try "Checkout Windows-Style, commit Unix-style".

Does this seem related to your problem, or is it something else?

**Comment by frankhale** [comment]
I'm on Windows, it could be that I forgot to turn on autocrlf within Github
for Windows for this project. I'll check. My number one problem with Git on
Windows is line ending normalization. Even when you do what is recommended
by Github it sometimes is not enough.
