### ISSUE TITLE
Testing expression in if produces stack overflow

### ISSUE THREAD

**Issue by mrwizard82d1** [vsClojure/vsClojure#152]
When I add the following script to a page, it produces a stack overflow error in the browser:

(ns truth-test.test)

(def true-item :true)

(def false-item nil)

(def return-true "true")
(def return-false "false")

(defn single-true-item-test [](if true-item
    return-true))

(defn single-false-item-test [](if false-item
    return-true
    return-false))

;; Initialization for page (sets the form submission validation function).
(defn init
  "Initializes the page by setting the form submission validation function."
  [](single-true-item-test))

;; Initialize the page in an unobtrusize way
(set! (.-onload js/window) init)

When I look at the compiled code for core.cljs (from the 0.0-2173 source code), I see the following definition for cljs.core.truth:

cljs.core.truth_ = (function truth_(x){
return cljs.core.truth_.call(null,x);
});

However, when I look at the code generated by the JVM ClojureScript compiler, I see the following definition:

cljs.core.truth_ = function truth_(x) {
  return x != null && x !== false;
};

**Comment by frankhale** [comment]
I don't know what is causing this but the first thing I'd do is remove the old version of Clojurescript that is being shipped with vsClojure and use a more recent version. Maybe it's because of bugs in Clojurescript? I dunno. This is quite easy to do, if you clone this repo you can get a more recent version but you'll have to had unzip it and put it in the runtimes folder where the vsClojure extension is installed. Or you can roll your own build of Clojurescript by following the build instructions on the Clojurescript Github repo. 

The path to where the runtimes are will vary from system to system. But this should point you in the right direction:

```
C:\Users\Frank\AppData\Local\Microsoft\VisualStudio\12.0\Extensions\<random_dir_name>\Runtimes
```

Replace the ClojureScript-1.5.0 runtime. Basically just dump a new version of the compiler and supporting files in that folder.

Maybe this will resolve the issue, I'm not sure but what I do know is that the current Clojurescript (as far as I can tell) is seriously old.

**Comment by mrwizard82d1** [comment]
Thanks, Frank.

I did not realize that the .NET version of the ClojureScript run time was old. I will look into these updates. I'm curious, what version of the released run time is up-to-date?

Yesterday, i actually tried to build vsClojure from source; however, I ran into an issue: the vsClojure  project fro ClojureScript requires, I think, Visual Studio 2013. 

Based on your explanation, I do not think I'll encounter a similar issue. I assume that if I decided to build ClojureScript from scratch, my version of Visual Studio will not matter.

Thanks, again, for your help.

Have a great day!

**Comment by frankhale** [comment]
Hi,

Clojurescript doesn't depend on .NET. I can pull the latest Clojurescript
compiler and include it in the vsClojure repository tonight when I get
home. In lieu of that here is a recent build of the Clojurescript compiler.
This represents a snapshot from the upstream repo. It's newer than 0.0-2173
which is their currently official release.

https://github.com/vsClojure/vsClojure/blob/master/ClojureExtension.Deployment/Runtimes/Clojurescript-Current-2March2014.zip

You could unzip this and put it in the Clojurescript-1.5.0 folder as I
previously explained. The bug you encountered may be due to an old version
of Clojurescript. I just wanted to see if you could try that and see if you
still experience a problem.

**Comment by mrwizard82d1** [comment]
Thanks, Frank.

I'll try these run times a bit later this morning.

Have a great day!

**Comment by mrwizard82d1** [comment]
Eureka! It worked.

Thanks, Frank.

Have a great day!

**Comment by frankhale** [comment]
AWESOME! Have a great day as well!!!

**Comment by frankhale** [comment]
Hi Larry, 

I've included a current build of the Clojurescript compiler. If you clone this repo you can grab the zip file and use it instead if you like.

The file is located in the followiing place in the code:

ClojureExtension.Deployment/Runtimes/
