### ISSUE TITLE
ClojureCLR patch

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#160]
Is there any way we can eliminate the need for the special patch that has been applied to the ClojureCLR compiler? It'd be very nice if we could just use Nuget to manage the ClojureCLR dependency instead of by hand.

**Comment by frankhale** [comment]
When I use ClojureCLR from the command line I'm not dependent on any extra patches. I just use it as it is. I don't think vsClojure should be doing any special patching to the Clojure compiler to make it work.

**Comment by speige** [comment]
The purpose of the custom patch is to allow ClojureCLR to compile multiple .clj files into the same .dll or .exe. This is useful when creating .cljproj files, if a programmer doesn't want all of their code in the same namespace and .clj file. If it's not done this way, adding a reference from one project to another in visual studio is cumbersome.

The custom patch has been submitted as a pull request to ClojureCLR to David Miller. He really likes the feature, however it caused a unit test to fail. He didn't want to commit it to the core ClojureCLR compiler until the unit test was fixed.

**Comment by frankhale** [comment]
Pull requests will never be honored in Clojure because Rich Hickey doesn't
want to track changes like that. Anyone that submits a patch has to sign
the contributor agreement and send it physically to Rich Hickey so he can
keep it on file. Patches have to be submitted to the official JIRA website
and then has to be vetted by more than one person before being committed.

I guess the big question is, what does the JVM version do and if it doesn't
do that does the CLR version need to do it? Can any compromise be thought
about in order to use the compiler as it is in it's official capacity?

**Comment by speige** [comment]
I'm not sure how the JVM handles compilation in this scenario. I don't think ClojureCLR compiler & ClojureJVM compiler are not identical. But, David Miller tries to keep them as similar as possible.

I do have a contributor agreement signed with Rich Hickey. I did submit the pull request through JIRA.

I think Rich has delegated administration of ClojureCLR to David Miller.

**Comment by frankhale** [comment]
That's awesome! And you probably told me that before and I forgot. But it's
already been a very long time and nobody has made a move on the patch. If
it was my patch I would have scrapped it a long time ago due to not wanting
to wait for slow development process of Clojure. I'd find a new way that
doesn't require changes to the compiler.

Have you looked at this?

"A Leiningen plugin to automate build tasks for ClojureCLR projects."

https://github.com/kumarshantanu/lein-clr

My current stumbling block for vsClojure is this separate build process
that does things in a Visual Studio way. I'm not sure I want to write
Clojure and build projects in a Visual Studio way. I'd rather use the
Clojure way, eg. Leiningen. LOL!

In the JVM land let's say for Eclipse and IntelliJ IDEA the Clojure support
also has Leiningen support built in. When you build projects you build the
structure of the project is done in a nice way through Leiningen. I may be
over simplifying things but I think at the end of the day are people coming
to Clojure going to want to switch their mental context to "The .NET Way",
 "The Visual Studio Way" or are they going to just want to do it "The
Clojure Way"?

I'm being cynical here for the sake of asking these kinds of design
specific questions. Do we ultimately want some new way to develop Clojure
on .NET that deviates from the traditional way it's already being done? I
understand the need for msbuild configurations and what not but as a .NET
developer myself I don't want that for Clojure. MSBuild is far too
cumbersome and not at all easy to hand edit, however, Leiningen project.clj
files are drop dead easy to edit.

Anyway I don't know where I'm going with this, just trying to pose
questions.

**Comment by speige** [comment]
I agree with you on changing vsClojure to use leiningen instead of msBuild. I was hesitant at first, because I had never tried leiningen, because I had never used ClojureJVM only ClojureCLR.

I tried lein in eclipse a week ago, & I agree it's way easier than msbuild.

I'm not sure what steps are required to convert vsClojure to use leiningen instead of msbuild, but we should research that.

It'd also make it easier for developers to switch between visual studio & the command line or another ide. Also, we'd get some things for free (like downloading third-party references & dependencies)

I'll take a look at at the lein-clr you posted. I know aaronc also worked on something similar.

**Comment by speige** [comment]
I wonder how leinClr will handle compiling multiple .clj into a single .dll or .exe. We should check to see if that works or not. I know ClojureCLR compiler doesn't support it without the custom patch.

David is happy to add it to the compiler if I fix the unit test. He's very responsive. I just hadn't got around to looking at the unit test yet.

So much to do, so little time :(

**Comment by frankhale** [comment]
Okay if the custom patch is necessary let's push now to get it incorporated
into ClojureCLR upstream. Let's put every other issue on hold and do
whatever is necessary to get the patch applied. This way we can dump our
hand jammed compiler from the dependencies and manage that using Nuget.

**Comment by frankhale** [comment]
I just hand patched the ClojureCLR 1.6.0 master and will zip up the binaries and add them to the Runtimes folder.

**Comment by frankhale** [comment]
ILMerge doesn't seem to work in 1.6.0 master. Maybe you can give it a shot. Otherwise I'll just zip up the default way it compiles. I've built 1.4.0 release. It looks like the configuration in the build.proj is wrong for the ILMerge command. All those DLL's are no longer being built. There is a Clojure directory with tons of CLJ files. That's always been the case so I don't know what exactly is wrong (yet).

**Comment by speige** [comment]
It has always worked for me, but I haven't tried it on 1.6. The only error I usually get is that the edn file is missing, but it can be fixed by adding edn to the post-build event in one of the .csproj files

Instructions:

a) Make sure ilmerge is installed on the path (I recommend using Chocolatey nuget to do this: http://chocolatey.org/packages/ilmerge)

b) Set the CLOJURE_SNK environment variable to the path of a private key file for strong name signing (you may need to generate an snk if you don't already have one for this, see: http://msdn.microsoft.com/en-us/library/6f05ezxy(v=vs.100).aspx)

c) Open a Visual Studio command prompt and run (from the directory Clojure where build.proj lives):

msbuild /t:Ilmerge /p:Configuration="Release 4.0" build.proj

You should find an ILMerge'd signed Clojure.dll in the bin/4.0/Release/ilmerge directory.

**Comment by frankhale** [comment]
Yeah I copied those instructions to a Wiki page 3 months ago.

https://github.com/vsClojure/vsClojure/wiki/ILMerge-ClojureCLR

ClojureCLR builds fine with the patch hand applied. It works. It just will
not ILMerge due to the fact that all those intermediate DLL's that are
annotated in the ILMerge command in build.proj are not created. It could be
I'm doing something wrong but ClojureCLR compiles fine in Visual Studio and
I can run the REPL and what not.

**Comment by frankhale** [comment]
I'm pretty much available all day long on Google Chat if that would be a
better mechanism to talk casually about vsClojure. I can see you in my list
of contacts. Let me know if that is a good mechanism for you to chat on.
