### ISSUE TITLE
Please consider adding support for Visual Studio 2014 installation

### ISSUE THREAD

**Issue by ghost** [vsClojure/vsClojure#169]

**Comment by frankhale** [comment]
I don't have a copy of Visual Studio 2014, I'd be more than willing to accept a pull request adding this support. Closing this for now.

**Comment by ghost** [comment]
Fair enough :-)

**Comment by frankhale** [comment]
In all seriousness since there is no community behind this project right now and no development happening it'd be unlikely that this would come any time soon even with a copy of VS2014. The code base needs some major love and there are numerous bugs that have still yet to be investigated. I've tried to revive the project asking the community multiple times but nobody seems interested in ClojureCLR support in Visual Studio. When I say interested I mean willing to help navigate the slippery slopes of writing VS extensions.

**Comment by ghost** [comment]
I totally understand that. I'm giving it a quick look now...
