### ISSUE TITLE
Automatic restart after installation

### ISSUE THREAD

**Issue by jmis** [vsClojure/vsClojure#56]
Users currently need to manually restart Visual Studio after the installation process.  We can use the Restart method on the IVsShell4 interface to restart the IDE automatically.  See the installer for an example usage.

**Comment by frankhale** [comment]
```
See the installer for an example usage.
```

Okay, I did that but I don't see any example of using the IVsShell4 interface to restart VS. That's okay, I can Google.

**Comment by frankhale** [comment]
This is all that is needed to restart Visual Studio after the installation is complete:

``` csharp
var shell = (IVsShell4)GetService(typeof(SVsShell));
shell.Restart((uint)__VSRESTARTTYPE.RESTART_Normal);
```

However, the code to determine if a restart is required seems problematic and the restart will just go in a loop always prompting.

The code in question is in the ClojurePackage.cs file in the Deployment project in the following function:

```
EnableSettingOfRuntimePathForNewClojureProjects
```

Here is the exact function with the restart code placed in the appropriate spot based on the already existing code:

This works great but we need a better way to determine when a restart is required. This causes and infinite loop of restarting.

``` csharp
private void EnableSettingOfRuntimePathForNewClojureProjects(out bool restartRequired)
{
    string deployDirectory = GetDirectoryOfDeployedContents();
    string runtimePath = deployDirectory + "\\Runtimes";
    string clrRuntimePath1_5_0 = string.Format("{0}\\{1}-{2}", runtimePath, Constants.CLOJURECLR, Constants.VERSION);

    bool runtimePathIncorrect = EnvironmentVariables.VsClojureRuntimesDir != runtimePath;
    if (runtimePathIncorrect)
    {
        EnvironmentVariables.VsClojureRuntimesDir = runtimePath;
    }

    string extensionsDirectory = Directory.GetParent(deployDirectory).FullName;

    restartRequired = runtimePathIncorrect;
    if (restartRequired)
    {
        if (MessageBox.Show("Setup of vsClojure complete.  Please restart Visual Studio.", "vsClojure Setup") == DialogResult.OK)
        {
            var shell = (IVsShell4)GetService(typeof(SVsShell));
            shell.Restart((uint)__VSRESTARTTYPE.RESTART_Normal);
        }
    }
}
```

**Comment by frankhale** [comment]
Okay so I added some code to resolve the restarting and the checking to see if we need to restart. If there is a better method to determine if we need a restart I'm all ears. I'll leave this open for a time to see if any problems crop up.

**Comment by speige** [comment]
I'm surprised you were experiencing an infinite restart. On my box, I only see the "please restart visual studio" message 1X after installing the plugin (or updating to a new version). However, I have noticed that if I install it in VS2012 & VS2013, every time I switch from one to the other I get the message.

I'll take a look on my box later & see how your new code works for me.

**Comment by frankhale** [comment]
Yeah not sure why but I changed the code around a bit to prevent it.

**Comment by speige** [comment]
I was working on this today and caused the same infinite restart you were seeing earlier. I understand what you were saying now. It turns out that the restart command for some reason wasn't re-loading the environment variables, so it would keep re-trying to set them over & over again. However, I found that you can modify an environment variable in the currently running process, which prevents the need to restart in the first place. I've committed this fix. Now only 1 restart will be required, not 2. (unless you install the .vsix while visual studio is closed, in which case, no restart is necessary).

The environment variable is used in 3 places. To compile a clojure project, to load a REPL, and to show intellisense when editing a .clj file. We could probably change the REPL/Intellisense to grab it from the project properties, instead of the environment variable, but I'm not sure what alternative there is for MSBuild yet. However, since the restart isn't necessary, I don't think the environment variable is a problem anymore.

**Comment by frankhale** [comment]
Can the environment variable instead be put into a registry key to avoid a VS restart?

**Comment by speige** [comment]
The only restart now is done automatically by visual studio, not requested by our code. I'm not sure if there's any way to avoid it. I think all extensions do it when installed directly inside the visual studio extensions tab.

It could be moved to a registry key, but since we removed the need to restart already, I don't know if there would be any benefit to it.

**Comment by frankhale** [comment]
Oh okay, I didn't realize that you reworked the code to prevent a special
restart because of env variables.
