### ISSUE TITLE
Can't start Clojure REPL from non Clojure project

### ISSUE THREAD

**Issue by frankhale** [vsClojure/vsClojure#96]
The "Start Clojure Repl" menu item shows on the project context menu but if you try to start the Clojure Repl outside of a Clojure project you get the following error. See screenshot below.

Additionally, I'd make a motion to move that menu item from the project context menu and put it under the View menu and have it work in the same manner as F# interactive. What I mean by that is that the Clojure REPL should be able to be opened in any context just like you can with F# Interactive.

![errorstartingclojurereplfromnonclojureproject](https://f.cloud.github.com/assets/190154/1716990/8eae9b4e-61c9-11e3-9c5b-3a0f3983c010.png)

**Comment by frankhale** [comment]
I've actually figured out why this fails and it's due to environment variables that are being assumed to be there. Specifically the path to the Clojure.Main.exe. Maybe we should put the environment variables in the registry and just read them from there?

**Comment by frankhale** [comment]
Actually, I'm a little mistaken in what I am claiming as environment variables. The offending code originates in the ShowClojureProjectMenuCommands() function in ClojurePackage.cs. The annonymous function that creates a new LaunchParametersBuilder is the one failing. This function should return a path that is used to create the REPL instance. Couldn't we just eliminate this altogether and use the CLOJURE_LOAD_PATH environment variable which is set by the vsClojure installer. I'm going to rework the code to use this instead of the failing call and see how it goes. As a side note, I've hard coded the path and it worked fine and the REPL opened outside of a Clojure project so I think using the env variable will work fine as well.

**Comment by speige** [comment]
That makes sense. Let me know if you're able to get it fixed.

The only reason an environment variable is created is because it's used in
the .cljproj msbuild tasks for compilation. The frustrating part of the
environment variable is that it requires a visual studio reboot after being
set, so I'd love to get rid of it. But, I'm not sure an easy way around it
for msbuild.

**Comment by frankhale** [comment]
Should the function EnableSettingOfRuntimePathForNewClojureProjects in ClojurePackage.cs be appending to the CLOJURE_LOAD_PATH environment variable or simply blowing it away and adding just one path? I'm seeing on my system that I have multiple paths in there and it doesn't quite make sense. It's because I believe I installed vsClojure in both VS2012 and 2013. I think it should probably only have one path to the Clojure runtime in there. Your thoughts?

**Comment by speige** [comment]
It appends it in case you have it installed in multiple versions of visual
studio. Otherwise, every time you switch versions of VS it'll tell you to
restart. However, when it actually compiles it probably just uses the 1st
one, so it doesn't really make sense. It'd be nice to completely remove the
environment variable if we can find an alternative for msBuild.

**Comment by frankhale** [comment]
What about installing the Clojure runtime files in a predictable place that
any Visual Studio running the extension could then use? The thing that
seems problematic is the wacky random directory that the runtime files get
installed into based on what VS version you install the extension in.
Perhaps the runtime files could go into the Program Files folder?

**Comment by dmiller** [comment]
Using the NuGet system in VS does not canonicalize placement?

**Comment by frankhale** [comment]
Hi David, the vsClojure extension also installs it's own Clojure runtime files in:

C:\Users<UserName>\AppData\Local\Microsoft\VisualStudio<VSVersion>\Extensions<RandomDirectory>\runtimes

**Comment by dmiller** [comment]
Possibly the NuGet package should be the default going forward?

**Comment by frankhale** [comment]
I'm inclined to agree with that. I think defaulting to the nuget is probably the best route rather than shipping Clojure with the extension.

**Comment by speige** [comment]
I believe nuGet adds the .dlls to the current solution, it doesn't install
clojure to a specific folder.

We essentially are using the nuGet binaries, but rather than requiring the
user to install them onto each solution, we install them at a central
location, relative to the visual studio extension folder.

vsClojure can be compiled with the nuGet package & use the referenced dlls
for 99% of what it does, because the referenced nuGet dlls are copied to
bin and deployed along with the extension. However, when the end user
compiles a clojure solution (with .cljproj fie), MSBuild is run completely
out of process from vsClojure. It calls Clojure.Compile.exe on each .clj
file. To do this, MSBuild needs the physical path to Clojure.Compile.exe,
but it doesn't know the vsClojure install directory. The code currently
uses an environment variable containing the install path to communicate
between vsClojure & MSBuild, but I have an open issue in github to
determine if there's another way around that. Although it could be put on
%path%, that would prevent having side-by-side vsClojure projects of
Clojure 1.5 & Clojure 1.6, however, I'm not sure how many people care to
stick with older versions.

Another option would be to require the nuGet binaries & tools
(Clojure.Main.Exe & Clojure.Compile.exe) to be located on a relative path
to each project in the solution. We could automate this for the user by
including the nuGet packages.xml in the vsClojure project templates. The
benefit to this would be allowing the user to check in the ClojureCLR
binaries to their version control & maintain it on their own (obviously
with the ability to update from nuGet). This way, if nuGet or vsClojure are
not kept up to date, it's obvious to the user how to maintain their own
solution. The only downside is vsClojure would be dependent on the user
having nuGet installed into visual studio.

**Comment by frankhale** [comment]
What about storing the Clojure runtime in a predictable place like C:\Program Files\ClojureCLR as well as adding it to the path. The thing that makes me leery is the random directory that Visual Studio puts the runtime in. I think that adds a layer of complexity to the maintenance of vsClojure because the runtime is in a non obvious place. I ran into some issues with some tiny projects after uninstalling and reinstalling vsClojure and the projects could no longer find Clojure.Compile. It could have just been my mucking around but I'm not sure.

On the other hand I like to think that the Clojure runtime is just a dependency like any other and should be maintained by nuget since that is what the community has already decided upon for dependency management. This could fulfill what you talk about in your last paragraph and it'd just be up to us to figure out how to massage vsClojure to work with a Clojure runtime installed within the project.

Of course I could be way off base but I'm just trying to lubricate the gears of idea creation.

**Comment by speige** [comment]
It would definitely be easier for MSBuild to have the ClojureCLR dependencies in a consistent place.

I like the idea of vsClojure being self-contained without needing to do a separate install. For Clojure to get much traction, it needs to be easy for programmers to jump in & get started. I don't mind grabbing the dlls from nuGet & embedding them into vsClojure, but that should be on my side, not the end user. I don't want to require the user to download nuGet & find the Clojure package, and follow a set of instructions on how to set up their solution. I think vsClojure should just work out of the box.

I also like the idea of the tool vsClojure being disconnected from the specific ClojureCLR version the programmer chooses as his target during compilation. We should be able to push updates of vsClojure to users without the fear that their solutions will be auto-upgraded to a different version of ClojureCLR. It should be their choice to switch the target ClojureCLR version for compilation when they're ready.

Finally, it's nice to have all dependencies on a relative path to the solution, so it can be checked into source control. The benefit here is that the continuous integration doesn't need separate dependencies and you can guarantee that every developer on the team is working off the same dll versions, even if one developer forgot to update his vsClojure extension. Strong names on our dlls may give warnings when this happens, but probably wouldn't prevent it.

Although I have some reservations about nuGet, I know Microsoft is going with nuGet for a lot of their templates (ASP.NET MVC, for example). If we choose to use it, we'll need to test if nuGet works with .cljproj projects, since they're custom.

Note, that vsClojure does have primitive ClojureScript support, which we should keep in mind, but they don't necessarily have to follow the same pattern.

We could add a setting to the .cljproj project file on the right-click/properties menu to set the path to the ClojureCLR dependencies (which we can default to a directory of our choice). However, one fear is that would allow a user to shoot themselves in the foot by choosing distinct clojure target compilation versions for different clojure projects in the same solution. I don't see a valid use case for this, but having strong names would theoretically allow two copies of Clojure.dll to both be loaded into the AppDomain of an executable at runtime. However, because the files would both be named Clojure.dll, they couldn't both be copied into the bin folder.

I don't know what the right answer is yet. But, I'll keep thinking about it.

**Comment by frankhale** [comment]
Okay so back on track for this issue and just to reiterate. The "Start Clojure Repl" menu item shows up on the project context menu even when you are not in a Clojure project. If you are in a non Clojure project and click this menu item it will fail to open the repl. Basically the issue is that the code fails because it cannot get the path location of the repl because it's making assumptions that we have a valid vsClojure project open and there is some infrastructure (API) in there to provide this information. So in order to resolve this and I think you should be able to open a Clojure repl anytime in any project just like you can with F# Interactive we'll have to come up with a location that we can agree upon in order to store the Clojure runtime files.

My first instinct is to put it in C:\Program Files\ClojureCLR and then add this to the environment path as well.

I'd like to hear your thoughts on this.

**Comment by frankhale** [comment]
Actually I guess we could use the CLOJURE_LOAD_PATH environment variable that is created when installing vsClojure.

**Comment by frankhale** [comment]
I believe I've resolved this. Patch should be merged soon.

**Comment by speige** [comment]
I think that's the best way to go for the time being until we decide on
nuget vs Lein vs program files vs copy relative to cljproj on each
template

You'll want to also grab the runtime version from the cljproj or give
them a choice of which repl from the runtimes folder (1.5 vs 1.6 vs
clojurescript). For non cljproj right click, it could default to 1.6

Another option could be to remove it from the project right click & add
it to a vsclojure menu on the toolbar.

**Comment by frankhale** [comment]
I'm not sure I follow your last comment. You made a patch that removes CLOJURE_LOAD_PATH and your work made the patch I made irrelevant. Your code fixed the issue I was attempting to fix. No worries there.

**Comment by speige** [comment]
I wrote you an email explaining the miscommunication. I had been replying to issues all day yesterday through email, but I didn't realize GitHub wasn't updating the issues on the site. I'm not sure where my comments were going. I actually had written this comment by email before you made your change, but I added it manually a second time since it had been lost.

Sorry about that.

**Comment by frankhale** [comment]
Yeah that's crazy. No problem at all. I do a combination of reply from
email and replying on Github. I should probably check to make sure all the
stuff I've replied to is actually making it to the site.
